# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricacao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Compromissos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricacao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaInstitucional',
            fields=[
                ('agendas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.Agendas')),
                ('compromisso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromissos')),
            ],
            bases=('agenda.agendas',),
        ),
        migrations.CreateModel(
            name='AgendaPrivada',
            fields=[
                ('agendas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.Agendas')),
                ('compromisso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromissos')),
            ],
            bases=('agenda.agendas',),
        ),
        migrations.CreateModel(
            name='AgendaPublica',
            fields=[
                ('agendas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.Agendas')),
                ('compromisso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Compromissos')),
            ],
            bases=('agenda.agendas',),
        ),
        migrations.AddField(
            model_name='agendas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Usuario'),
        ),
    ]
